# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Software Blog 
tagline:          'Open source'
description:      'Thoughts about programming, open source and more'
url:              http://oscerd.github.io
baseurl:          /oscerd.github.io/

author:
  name:           'Andrea Cosentino'
  url:            https://twitter.com/oscerd2

paginate:         5

# Custom vars
version:          2.1.0

gems:
  - jekyll-seo-tag
  - jekyll-feed

github:
  repo:           https://github.com/oscerd/oscerd.github.io

theme: jekyll-theme-architect