# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Software Blog 
tagline:          'Open source'
description:      'Thoughts about programming, open source and more'
url:              http://oscerd.github.io
baseurl:          ''

author:
  name:           'Andrea Cosentino'
  url:            https://twitter.com/oscerd2

paginate:         5

# Custom vars
version:          2.1.0

gems:
  - jekyll-seo-tag
  - jekyll-feed

github:
  repo:           https://github.com/oscerd/oscerd.github.io
